# Generated by Django 3.0.8 on 2020-07-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('F', 'facebook'), ('W', 'whatsapp'), ('T', 'twitter'), ('G', 'telegram'), ('I', 'instagram'), ('L', 'LinkedIn')], max_length=1)),
                ('link', models.URLField()),
            ],
        ),
    ]
