# Generated by Django 3.0.8 on 2020-07-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('F', 'Facebook'), ('W', 'Whatsapp'), ('T', 'Twitter'), ('I', 'Instagram'), ('L', 'LinkedIn'), ('Y', 'Youtube')], max_length=1)),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
